### PR TITLE
Fix attr name in Unfuse.cpp

### PR DESCRIPTION
**Pull request by oowekyala**
names of those attrs in linalg take an *s*

### CODE REVIEW

**Comment by KFAFSP** [comment]
Oh my god, you are correct. Seems that the new fused ops are using the wrong naming convention! They all drop the s.

What's extra weird is that this worked.

**Comment by KFAFSP** [comment]
This should have failed during attribute verification... I'm very weirded out by this, have you tested it?

https://github.com/ljfitz/llvm-project/blob/karlf.FXML-699.linalg-fused/mlir/lib/Dialect/Linalg/IR/LinalgDialect.cpp#L160

**Comment by oowekyala** [comment]
> This should have failed during attribute verification... I'm very weirded out by this, have you tested it?

> [https://github.com/ljfitz/llvm-project/blob/karlf.FXML-699.linalg-fused/mlir/lib/Dialect/Linalg/IR/LinalgDialect.cpp#L160](https://github.com/ljfitz/llvm-project/blob/karlf.FXML-699.linalg-fused/mlir/lib/Dialect/Linalg/IR/LinalgDialect.cpp?rgh-link-date=2022-06-28T11%3A36%3A45Z#L160)

yeah this is weird, but for that matter neither `stride` nor `strides` (resp. `dilation`) are there in this method... I wonder if this method is just a callback called from tableGen for some specific op

**Comment by KFAFSP** [comment]
Actually, it was me who is stupid. This verifier is called only for attributes that are prefixed by the dialect namespace. So, all is well.

**Comment by oowekyala** [comment]
I initially opened it against feature/fused-ops, I'll reset to there (4545d3b)

**Pull request merged**
